
package main.project;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SelectServiceDAO_disconnect", targetNamespace = "http://project.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SelectServiceDAODisconnect {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServices", targetNamespace = "http://project.main/", className = "main.project.GetServices")
    @ResponseWrapper(localName = "getServicesResponse", targetNamespace = "http://project.main/", className = "main.project.GetServicesResponse")
    @Action(input = "http://project.main/SelectServiceDAO_disconnect/getServicesRequest", output = "http://project.main/SelectServiceDAO_disconnect/getServicesResponse")
    public List<String> getServices(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertOrder", targetNamespace = "http://project.main/", className = "main.project.InsertOrder")
    @ResponseWrapper(localName = "insertOrderResponse", targetNamespace = "http://project.main/", className = "main.project.InsertOrderResponse")
    @Action(input = "http://project.main/SelectServiceDAO_disconnect/insertOrderRequest", output = "http://project.main/SelectServiceDAO_disconnect/insertOrderResponse")
    public String insertOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceId", targetNamespace = "http://project.main/", className = "main.project.GetServiceId")
    @ResponseWrapper(localName = "getServiceIdResponse", targetNamespace = "http://project.main/", className = "main.project.GetServiceIdResponse")
    @Action(input = "http://project.main/SelectServiceDAO_disconnect/getServiceIdRequest", output = "http://project.main/SelectServiceDAO_disconnect/getServiceIdResponse")
    public List<String> getServiceId(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

}
